# Generated by Django 3.2.18 on 2023-02-27 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recepie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recepie',
            new_name='Recipe',
        ),
    ]
